### ISSUE TITLE
novas rotas do aeroplano

### ISSUE THREAD

**Issue by vitorsilverio** [eventMacrosBR/up_1_ao_99_todas_classes-bro#100]
NPC: izlude 206 55 
r0 r0

NPC: Assistente do Aeroporto
lhz_airport 143 33
r0 r0
NPC: Assistente de Desembarq
lhz_airport 143 49

Hugel Portal para Aeroplano: hugel 177...179 143
r0

**Comment by Nipodemos** [comment]
uai gente pra que isso
a de hugel não ta funfando os próprios portais normal não?
ou é tipo rachel que tem que pisar e clicar em sim?

**Comment by Nipodemos** [comment]
e esses goto me dão nos nervos também! tão dificil de ler mano que isso

**Comment by vitorsilverio** [comment]
Não tem uma função hugelPara para sair de lá, sim é um portal

2018-05-13 22:00 GMT-03:00 Nipodemos <notifications@github.com>:

**Comment by Nipodemos** [comment]
mano... perdi o código que eu tava fazendo pra ir pra hugel T_T
o PC desligou todo bem no meio tempo que eu tinha completado e ia commitar... droga

**Comment by vitorsilverio** [comment]
paciência, você consegue de novo, vai salvando, mesmo que não vá commitar

**Comment by Nipodemos** [comment]
esse código da macro aí é feio demais kkkk
nossa é quase impossível de entender oq ta rolando

**Comment by Nipodemos** [comment]
Adicionado todas essas rotas!!!
porem é necessário teste ainda, portanto não vou fechar esse issue
