### ISSUE TITLE
[Caçador] Adestrar Falcão

### ISSUE THREAD

**Issue by rafaelldavid** [eventMacrosBR/up_1_ao_99_todas_classes-bro#102]
Depois que já tiver a skill Flagelo das Feras Nv. 1, já pode ir adestrar seu falcão, que pode ajudar com ataques automáticos.

(Preciso pegar a coordenada exata, mas é na Guilda dos Caçadores em Hugel - 2ª andar)

**Comment by Nipodemos** [comment]
saudade da época que era la nos guardiao da floresta

**Comment by rafaelldavid** [comment]
Ah, com a macro de ir pra hugel pronta, ficou tão fácil quanto! kkkkkkkkkkkkkkkk

**Comment by Nipodemos** [comment]
@rafaelldavid ja fez :smile:
