### ISSUE TITLE
[Lembrete]Adicionar a compra de poções para Classes trans

### ISSUE THREAD

**Issue by Nipodemos** [eventMacrosBR/up_1_ao_99_todas_classes-bro#104]
atualmente nem classe 1 T nem classe 2 T são configurados pra usar e comrpar poções
deveria ser feito isso

**Comment by Nipodemos** [comment]
acho que agora esse issue ta resolvido, mas tem que testar ainda

**Comment by cogumm** [comment]
Opa foi resolvido essa issue?

**Comment by Nipodemos** [comment]
pior que ninguem testou... isso que é foda

**Comment by vitorsilverio** [comment]
Fechando por ter uma possível implementação e falta de testes, caso exista realemtne um problema alguém provavelmente reportará
