### ISSUE TITLE
[Sentinela] Compra de Flechas após virar Caçador

### ISSUE THREAD

**Issue by rafaelldavid** [eventMacrosBR/up_1_ao_99_todas_classes-bro#105]
Meu arqueiro que acabou de virar caçador está upando em izdun, mas vai comprar flechas em payon... kkkkkkkkkkkkk

Configurar pra ele comprar em izlude mesmo.

**Comment by rafaelldavid** [comment]
autoSell em payon também!

**Comment by Nipodemos** [comment]
uai que estranho... não está configurando?

poderia me mostrar seu bloco de buyAuto como está no config.txt?

**Comment by vitorsilverio** [comment]
meu buyAuto não funciona mais tambem, além disso ele fica chamando o aeroplano_hugelPara toda hora pela macro upar

**Comment by Nipodemos** [comment]
estranho é que não deveria... triste viu

**Comment by rafaelldavid** [comment]
Muita treta vish... kkkkkkkkkkk

**Comment by vitorsilverio** [comment]
Este issue será fechado agora, caso o problema persistir por favor reabra
