### ISSUE TITLE
[Sentinela] Chamando aeroplano_hugelPara

### ISSUE THREAD

**Issue by ojuniorbezerra** [eventMacrosBR/up_1_ao_99_todas_classes-bro#106]
Olá,
O macro fez tudo certo até virar arqueiro no lvl 12, na guilda onde vira arqueiro ele parou.
Ele executa "upar" mas fica chamando aeroplano_hugelPara sem destino!
O &config(saveMap) e &config(lockMap) estão em branco.
Alguem pode me ajudar? Entendo um pouco de programação, mas não muito. kkk
Ele está entrando no else do "upar" e no primeiro if do else.

**Comment by ojuniorbezerra** [comment]
Muito obrigado e parabéns pelo trabalho!

**Comment by Nipodemos** [comment]
pronto, aceitaram a correção do bug, agora é só atualizar o openkroe igual é feito na atualizaçao semanal?

**Comment by vitorsilverio** [comment]
Este issue será fechado agora, caso o problema persistir por favor reabra

**Comment by vitorsilverio** [comment]
```
[eventMacro] Error in macro 'tempMacro291'
[eventMacro] Line index of the error '4'
[eventMacro] Script of the line 'if (&config(storageAuto_npc_steps) != &config(saveMap_sequenciaPraArmazenar)) do conf storageAuto_npc_steps &config(saveMap_sequenciaPraArmazenar)'
[eventMacro] Error message 'Unrecognized macro command'
```

**Comment by vitorsilverio** [comment]
https://github.com/eventMacrosBR/up_1_ao_99_todas_classes-bro/commit/ec85f6696f4f6fe5112c0bd6ac4c77cdd537647b Corrigiu
