### ISSUE TITLE
Erro EventMacro 889.9ac3038 \ renegado.funcionando.zip

### ISSUE THREAD

**Issue by iroshimasan** [eventMacrosBR/up_1_ao_99_todas_classes-bro#108]
![erro](https://user-images.githubusercontent.com/13550363/40281303-75e2f968-5c36-11e8-8a8a-b0b6b9e3ee02.png)

**Comment by vitorsilverio** [comment]
poderia testar se na ultima versão ainda acontece?

**Comment by Nipodemos** [comment]
to conversando com ele no discord
vamos ver se ainda acnotece na última versão

**Comment by Nipodemos** [comment]
mano, aconteceu mesmo atualizado
vou ter que ver isso eu mesmo

**Comment by iroshimasan** [comment]
Ate agora rodando sem erro

**Comment by vitorsilverio** [comment]
estou fechando o issue se o erro voltar por favor reabra o issue

**Comment by Nipodemos** [comment]
o erro se resolveu :D
