### ISSUE TITLE
940.61c4e63: Merge pull request #114 from lksoliver/arcano-projeto

### ISSUE THREAD

**Issue by iroshimasan** [eventMacrosBR/up_1_ao_99_todas_classes-bro#115]
![erro1](https://user-images.githubusercontent.com/13550363/40514718-a61b04ca-5f80-11e8-849b-518c729acad0.png)

**Comment by vitorsilverio** [comment]
já vi o problema e vou submeter uma correção

**Comment by vitorsilverio** [comment]
A versão 942 apresentará as correções do problema
