### ISSUE TITLE
942.0ae32ba

### ISSUE THREAD

**Issue by iroshimasan** [eventMacrosBR/up_1_ao_99_todas_classes-bro#116]
![erro 2](https://user-images.githubusercontent.com/13550363/40516880-0e98ca8e-5f89-11e8-8515-cbb801ee8603.png)

**Comment by iroshimasan** [comment]
![erro3](https://user-images.githubusercontent.com/13550363/40517183-53a253c4-5f8a-11e8-9eb0-8ecfe8848538.png)

**Comment by vitorsilverio** [comment]
muito esquisito, acho que deu um erro no gerador de release, mandei ele regerar como versão 943. porque essa linha que deu erro nem é mais assim

**Comment by iroshimasan** [comment]
[errors.txt](https://github.com/eventMacrosBR/up_1_ao_99_todas_classes-bro/files/2037362/errors.txt)

**Comment by iroshimasan** [comment]
Vitorsilveiro baixei a nova macro esta funcionando beleza agora o problema é que ele fica teleportando usando teleport do eden

**Comment by Nipodemos** [comment]
digite o seguinte comando no seu openkore:
`conf teleportAuto_maxDmg 100000`
