### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by mcdc32** [eventMacrosBR/up_1_ao_99_todas_classes-bro#117]
Olá, eu coloquei 3 bots para upar usando o seu macro, 2 deles estão Ok (são gatunos nvl 47 upando em Izlude) mas um deles ainda é aprendiz e está nivel 43 matando esporos, o que eu posso fazer?

**Comment by vitorsilverio** [comment]
qual a versão da macro utilizada?
esse terceiro você começou o bot do level 1 ou de outro nivel?
mande as ultimas linhas do seu config.txt aquela parte util para desenvolvedores

**Comment by mcdc32** [comment]
sim, os 3 começaram juntos nvl 1.
Estou usando a versão que foi lançada agr pouco.


######## Debugging options; only useful for developers ########

debug 0
debugPacket_unparsed 0
debugPacket_received 0
debugPacket_ro_sent 0
debugPacket_sent 0
debugPacket_exclude
debugPacket_include
debugPacket_include_dumpMethod
debugDomains
logToFile_Debug
logToFile_Errors
logToFile_Messages
logToFile_Warnings
history_max 50
gameGuard 1
macro_orphans terminate
questc2_implementada true
questc3_implementada false
versao_eventmacro_up_todas_as_classes_bro 943.2baa341
naSequenciaDeSalvamento false
current_npc kafra
quest_atual
o_que_estou_fazendo upando
membroDoEden sim
saveMap_sequenciaPraArmazenar
saveMap_desejado
saveMap_posicaoKafra
saveMap_posicaoNpcVenda
saveMap_posicaoNpcPraPocao
quest_eden

**Comment by Nipodemos** [comment]
kkkkkkkkkkkkkk aprendiz lvl 43? meo deos a que nivel de bug a macro chegou

**Comment by mcdc32** [comment]
Agora ele está travado em payon

https://ibb.co/mEwzFo

**Comment by mcdc32** [comment]
https://ibb.co/cyEx1T

**Comment by Nipodemos** [comment]
oh amigo, digita ese coamndo por favor:
`eventMacro auto questClasse1_virandoClasse1`
manda aqui o que aparece por favor

**Comment by mcdc32** [comment]
[eventMacro] Printing information about automacro 'questClasse1_virandoClasse1'.
Number of conditions: '4'
Has event type condition: 'no'
Number of true conditions: '3'
Number of false conditions: '1'
Is triggered: '0'
----  Parameters   ----
1 - priority: '0'
2 - overrideAI: '0'
3 - disabled: '0'
4 - time: '0'
5 - delay: '0'
6 - orphan: 'terminate'
7 - macro_delay: '1'
8 - run-once: '0'
9 - timeout: '0'
10 - CheckOnAI: 'auto'
11 - repeat: '1'
12 - call: 'tempMacro61'
13 - exclusive: '1'
----  Conditions   ----
1 - JobLevel: 'true'
2 - InMap: 'false'
3 - SkillLevel: 'true'
4 - JobID: 'true'
----  AI check states   ----
Check on AI off: 'no'
Check on AI manual: 'no'
Check on AI auto: 'yes'
----  End   ----

**Comment by mcdc32** [comment]
Olha eu apaguei a pasta control do meu bot que não funcionava e coloquei no lugar uma pasta control do meu bot que funciona, substituindo as informações de servidor poseidon, login, senha, etc. Parece que voltou a funcionar, mas esse bug n deixa de ser estranho. Se quiser alguma informação a mais para tentar evitar que isso ocorra novamente ou entender oq houve me contate.

**Comment by mcdc32** [comment]
Mas ele ainda é aprendiz e está upando normalmente como se fosse alguém na vida.

**Comment by vitorsilverio** [comment]
você saiu do campo de treinamento manualmente?

**Comment by rafaelldavid** [comment]
Aproveita e já faz um super aprendiz... Já tá quase lá! kkkkkkkkkkkkkkk

Brinks! =P

**Comment by vitorsilverio** [comment]
nova versão tem uma automacro para virar a classe 1 caso o bot por algum motivo saia pelo lugar errado no campo de treinamento. por favor verifique para que possamos fechar esse issue

**Comment by mcdc32** [comment]
Apareceu isso 
https://uploaddeimagens.com.br/imagens/tissue-png

**Comment by vitorsilverio** [comment]
removi a condição inválida

**Comment by mcdc32** [comment]
Agora sim eu tenho um gatuno. Muito obrigado pela atenção e paciência de me ajudar aqui.

**Comment by vitorsilverio** [comment]
:D
