### ISSUE TITLE
lembrete

### ISSUE THREAD

**Issue by Nipodemos** [eventMacrosBR/up_1_ao_99_todas_classes-bro#12]
gostaria de te lembrar, que ainda nao temos quest eden pra todas as classes @vitorsilverio

**Comment by Nipodemos** [comment]
na verdade é igual sim, só precisa alterar a última parte que é a de pegar os equips

pra que um sacerdote possa pegar um cajado, e um ferreiro possa pegar machado por exemplo
na verdade é super simples adaptar isso, só criar uma nova variavel e usar, se pá eu faço isso hoje a noite se eu animar

**Comment by vitorsilverio** [comment]
Vai colocar o eden novamente?

**Comment by Nipodemos** [comment]
Eu tenho que lembrar de fazer isso, mas esse issue como lembrete nem tá me lembrando
