### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by mcdc32** [eventMacrosBR/up_1_ao_99_todas_classes-bro#123]
Não sei se isso é exatamente um problema mas estou com um arruaceiro nivel 93 e um Algoz 96 e estão upando muito lentamente nos petites. É pra eles estarem la? Onde eu posso achar uma lista dos mapas que esse macro upa? Desculpa se é um issue idiota mas estou curioso.

Obrigado pela atenção.

**Comment by lksoliver** [comment]
Olár, Então bebe a macro tem suporte pra basicamente todos os mapas , tanto que tem a opção pra você alterar os locais. 
Pode ocasionar alguns bugs mudando os locais?
Sim e não !
Vira e meche eu mudo meus locais de UP desde que não use o aeroplano não buga ( isso é certeza haha)
Pode mudar a vontade, se aparecer algum bug traga ele pra gente com as 20 ultimas linhas do console do seu open kore / ou uma print da mesma. 
Bom UP!
Espero ter ajudado, é nessa que eu vou :*

**Comment by lksoliver** [comment]
Ah só pra completar os locais de UP para modificar se encontra logo no começo da evenMacro, já os mapas vc procura o nome em um db.
Recomendo o https://pt.ragnaplace.com/ que é bem completo :octocat:

**Comment by vitorsilverio** [comment]
Este não é um issue realmente e vou considerar a dúvida como respondida por isso estou fechando.
