### ISSUE TITLE
Bug na compra de pot em Al de Baran

### ISSUE THREAD

**Issue by mcdc32** [eventMacrosBR/up_1_ao_99_todas_classes-bro#128]
Olá queridos programadores que salvam nosso farm de dinheiros, tudo bem com vcs?

Hoje vim reportar um bug que acontece toda hora que meu bot vai comprar poções em Al de Baran. Ele entra na loja de utilidades, dai ele sai, dai ele entra, dai ele sai, dai ele entra,e então ele toma a decisão de sair, mas dai muda de idéia e volta. E fica nesse ciclo que eu até agora não sei o que acontece e tive que cancelar a compra de pots pois tenho que entrar no rag original e retirá-lo de lá manualmente para que volte a upar, e isso é um saco.

Me ajudem pfv, meu bot ficou 5 horas entrando e saindo da loja de utilidade.

Lá vai as linhas que eu não entendo:

######## Debugging options; only useful for developers ########

debug 0
debugPacket_unparsed 0
debugPacket_received 0
debugPacket_ro_sent 0
debugPacket_sent 0
debugPacket_exclude
debugPacket_include
debugPacket_include_dumpMethod
debugDomains
logToFile_Debug
logToFile_Errors
logToFile_Messages
logToFile_Warnings
history_max 50
gameGuard 1
macro_orphans terminate
questc2_implementada true
questc3_implementada false
versao_eventmacro_up_todas_as_classes_bro 999.edd49e8
naSequenciaDeSalvamento false
current_npc kafra
quest_atual
o_que_estou_fazendo upando
membroDoEden sim
saveMap_sequenciaPraArmazenar
saveMap_desejado
saveMap_posicaoKafra
saveMap_posicaoNpcVenda
saveMap_posicaoNpcPraPocao
quest_eden
buyAuto
npc
standpoint
distance 5
price
minAmount
maxAmount
batchSize
disabled 0
zeny
}

useSelf_skill TF_HIDING {
	lvl 10
	maxCastTime 0
	minCastTime 0
	hp
	sp >= 30
	homunculus_hp
	homunculus_sp
	homunculus_dead
	onAction
	whenStatusActive
	whenStatusInactive EFST_HIDING, EFST_POSTDELAY
	whenFollowing
	spirit
	amuletType
	aggressives >= 3
	monsters
	notMonsters
	monstersCount
	stopWhenHit
	inLockOnly
	notWhileSitting
	notInTown 0
	timeout 0
	disabled 0
	inInventory
	manualAI 0
	notOnAction
}

useSelf_skill RG_RAID {
	lvl 5
	maxCastTime 0
	minCastTime 0
	hp
	sp >= 20
	homunculus_hp
	homunculus_sp
	homunculus_dead
	onAction
	whenStatusActive EFST_HIDING
	whenStatusInactive EFST_POSTDELAY
	whenFollowing
	spirit
	amuletType
	aggressives
	monsters
	notMonsters
	monstersCount
	stopWhenHit
	inLockOnly
	notWhileSitting
	notInTown 0
	timeout 0
	disabled 0
	inInventory
	manualAI 0
	notOnAction
}

aeroplano1
aeroplano_macroChamada

Olha o print do benedito:

https://uploaddeimagens.com.br/imagens/bug-de-leve-png

**Comment by mcdc32** [comment]
Ah, e mesmo desativando a compra de pots ele continua entrando la, é como eu disse, tem que entrar no rag original e deixar ele bem longe da loja pra ele n voltar

**Comment by vitorsilverio** [comment]
```
buyAuto
npc
standpoint
distance 5
price
minAmount
maxAmount
batchSize
disabled 0
zeny
}
```
Isto aqui não foi a macro que gerou, e provavelmente está causando seu bug
Ou tinha gerado e voce apagou o item junto com o {

**Comment by Nipodemos** [comment]
deve ter resolvido, já que não houve resposta.
Fechando esse issue.
