### ISSUE TITLE
Referências

### ISSUE THREAD

**Issue by vitorsilverio** [eventMacrosBR/up_1_ao_99_todas_classes-bro#13]
Segue alguns macros para referencias de quests:
Sumo, Lorde, Criador e Desordeiro, No geral da para usá-la para transformar todas as transclasses, basta trocar a coordenada do npc final, ajuda a pegar builds também
http://openkorebrasil.org/index.php?/topic/3282-0-ao-99-transclasse-sumo-criador-lorde-e-desordeiro/

Quest de noviço e Sacer, podemos utilizar a parte do Sacer convertendo para EventMacro
http://openkorebrasil.org/index.php?/topic/3136-virar-novi%C3%A7o-e-sacer/

**Comment by vitorsilverio** [comment]
Lista dos npcs das quests:

Cavaleiro
NPCS
Chefe dos Cavaleiros prt_in 88 101
Cavaleiro Dedicado prt_in 75 107
Cavaleiro Honroso prt_in 71 91
Cavaleiro das Lutas prt_in 79 94
Cavaleira Educada prt_in 69 107
Cavaleiro Devotado prt_in 70 99
Cavaleiro Modesto prt_in 87 92

Templario
NPCS
Templário Sênior prt_castle 45 169
Homem Angustiado prt_castle 164 32
Templária prt_church 95 127
Bliant Piyord prt_castle 35 151

Sábios 
NPCS
Funcionário Acadêmico yuno_in03 154 35
Examinador Teórico yuno_in03 169 180
Examinador Prático yuno_in03 169 180
Professor de Biologia yuno_in03 32 102
Professor de História yuno_in03 62 176
Professor de Física yuno_in03 244 31
Presidente da Academia yuno_in02 38 61

Caçadores
NPCS
Caçadora da Guilda hu_in01 386 373
Recepcionista da Guilda hu_in01 382 382
Caçadora payon_in02 21 31
Caçadora payon_in03 131 7

Bardos
NPCS
Bardo Andarilho comodo 214 155
Papai Noel aldebaran 224 222
Garota do Natal xmas_in 165 173
Boneco de Neve xmas 134 112
Rapaz do Natal xmas 117 303
Tio Peludo xmas 176 236
Senhora Generosa xmas_in 27 102
Palhaço do Natal xmas 146 136
crianças xmas 207 168

Odaliscas
NPCS
Bor Roben comodo 193, 151
Ale job_duncer 43, 93
Borwaju job_duncer 95, 93
Sala de Espera job_duncer 32, 154

Ferreiros
NPCS
Mestre Ferreiro na Guilda dos Ferreiros ein_in01 18 28
Mestre Ferreiro ein_in01 201 27
Bismarc hugel 168 183
Talpiz payon 214 79
Baisulist geffen 46 164
Wickebine morocc 27 112
Krongast lighthalzen 209 80
Mestre Ferreira ein_in01 24 41

Monges
NPCS
Monge prt_monk 59 247
Monge Muhae monk_in 99 58
Dohua prt_monk 251 255
Puhae prt_monk 57 179
Assistente monk_test 329 61
Examinador job_monk 225 180
Taomon monk_test 319 139

**Comment by Nipodemos** [comment]
que lindo! fez o que eu nao tenho paciencia pra fazer!

**Comment by vitorsilverio** [comment]
Coordenadas npcs templo da valkiria para classe 2T
```
Lorde 44 39
Sumo Sacerdote 44 42
Paladino 53 39
Mestre 53 42
Arquimago 44 47
Mestre Ferreiro 44 50
Professor 53 47
Criador 53 50
Atirador de Elite 44 55
Algoz 44 58
Menestrel 53 54
Cigana 53 56
Desordeiro 53 58
```

**Comment by Nipodemos** [comment]
opa, top top top

**Comment by vitorsilverio** [comment]
Skills espadachims fonte : http://openkorebrasil.org/index.php?/topic/44-skills-espadachim-e-evol/
```perl
#Vigor
useSelf_skill SM_ENDURE {
lvl 10
hp
sp > 20
aggressives
monsters
}

#Rapidez_com_Duas_Mãos
#Esta Irá trabalhar com lança
useSelf_skill KN_TWOHANDQUICKEN {
lvl 10
sp > 10
whenStatusInactive Twohand Quicken
stopWhenHit 0 
inLockOnly 1
notWhileSitting 1
notInTown 1
timeout 300
}


#Curar
#Funcionará se o HP estiver menor que 50%
useSelf_skill HEAL {
lvl 10
hp < 50
}

#Medicar
#Isto funciona quando whenStatusActive é amaldiçoado , Silenced , cego ou Caos.
#useSelf_skill AL_CURE {
lvl 1
onAction
whenStatusActive Poisoned
}


#Redenção
#habilidade para grupo, até 5 alvos.
partySkill ML_DEVOTION {
lvl 5
sp > 20
whenFollowing
stopWhenHit 0
inLockOnly 0
notWhileSitting 0
target
target_hp
}
```

**Comment by vitorsilverio** [comment]
Cont.
```
useSelf_skill LK_TENSIONRELAX {
lvl 1
hp < 60%
monstersCount < 1
stopWhenHit 1
whenStatusInactive Action Delay
sp > 45%
aggressives < 1
}

useSelf_skill KN_TWOHANDQUICKEN {
lvl 10
sp > 30%
whenStatusInactive Two-Hand Quicken
stopWhenHit 0
inLockOnly 1
monstersCount >= 1
notWhileSitting 1
notInTown 1
}

useSelf_skill LK_CONCENTRATION {
lvl 5
sp > 30%
whenStatusInactive Concentration
stopWhenHit 0
inLockOnly 1
monstersCount >= 1
notWhileSitting 1
notInTown 1
}

useSelf_skill LK_AURABLADE {
lvl 5
sp > 30%
whenStatusInactive Aura Blade
stopWhenHit 0
inLockOnly 1
monstersCount >= 1
notWhileSitting 1
notInTown 1
}

useSelf_skill LK_PARRYING {
lvl 10
sp > 30%
whenStatusInactive Parrying
stopWhenHit 0
inLockOnly 1
monstersCount >= 1
notWhileSitting 1
notInTown 1
}
```

**Comment by vitorsilverio** [comment]
Algumas quests já prontas nesse post
http://openkorebrasil.org/index.php?/topic/3282-0-ao-99-transclasse-sumo-criador-lorde-e-desordeiro/

**Comment by vitorsilverio** [comment]
https://github.com/PoringUniverse/iro-restart-repo

**Comment by Nipodemos** [comment]
temos que manter isso mais ativo, tem umas informações interessantes até
principalemnte pra fazer as próximas classes 2

**Comment by vitorsilverio** [comment]
talvez passar parte desas informações para o README e para wiki

**Comment by vitorsilverio** [comment]
Queria fechar esse issue, tem alguma informação aqui que ainda mereça ter uma página na Wiki? @Nipodemos

**Comment by Nipodemos** [comment]
acredito que isso possa ser fechado sim
as informações não utilizadas são as que podem ser facilmente achadas, as outras já são usadas ou nunca vai usar
