### ISSUE TITLE
Cavaleiro de Agi com rapidez com duas mãos

### ISSUE THREAD

**Issue by Sudono369** [eventMacrosBR/up_1_ao_99_todas_classes-bro#137]
eu n conheço nda de git, mas comecei a fazer algumas mudanças no plugin pra tentar upar meu cavaleiro com uma build de agi e rapidez com duas mãos, mas não consegui... oq aconteceu foi ele ficar usando rapidez com duas mãos a kda 3 passos e n fez mais nda....

Alguem ai tentou algo parecido e conseguiu?

**Comment by Nipodemos** [comment]
e vc fez o bloco de rapidez de duas maos errados, já que a eventMacro não faz ele por padrão (é uma coisa que tem que ser feita ainda)

**Comment by vitorsilverio** [comment]
tem o código dessa mudança para vermos?

**Comment by Nipodemos** [comment]
adicionado um commit que colocou o bloco de rapidez com duas mãos
