### ISSUE TITLE
Melhor explicação de instalação

### ISSUE THREAD

**Issue by TolkienLabel** [eventMacrosBR/up_1_ao_99_todas_classes-bro#143]
Tudo bom ? primeiro obrigado pelo trabalho que está sendo posto aqui.
Eu sou novo nesse mundo e gostaria de saber como eu coloco esse macro pra rodar se alguém puder me dar um norte agradeço .

**Comment by vitorsilverio** [comment]
Olá, temos 2 opções de disponibilização:

1. Você pode clonar o projeto com git e executar o gerador referente ao seu sistema operacional
2. Você pode baixar a ultima versão já gerada para uma determinada classe em https://github.com/eventMacrosBR/up_1_ao_99_todas_classes-bro/releases

Após gerar (ou baixar) o arquivo eventMacros.txt, coloque-o na pasta control do seu openkore, algumas classes necessitam da instalação de plugins adicionais consulte aqui(https://github.com/eventMacrosBR/up_1_ao_99_todas_classes-bro/wiki/Plugins) baixe o plugin e coloque na pasta plugins do seu openkore.

A macro vai upar seu aprendiz até o level 99 fazendo as quests, ela consegue upar chars que já tenham algum certo level se a build e os equipamentos não forem muito diferentes. É importante que as unicas configurações que tenham sido feitas no seu openkore sejam referentes a login e ao poseidon ou hades.

**Comment by TolkienLabel** [comment]
Eu fiz tudo isso porém não sei executar o macro, uso openkore  . se pude ajudar agradeço mt

**Comment by vitorsilverio** [comment]
a macro se inicia sozinha basta estar na pasta control, você está utilizando o openkore mais atualizado do site https://github.com/Openkore/openkore ?

**Comment by TolkienLabel** [comment]
hm, ela não inicia ... coloquei dentro do conf e os plugins porém n acontece nada >C

**Comment by vitorsilverio** [comment]
Qual classe está tentando?
Você desativou o plugin eventMacros das configurações do openkore?
Está utilizando a versão oficial do openkore? (Não comprou ou baixou de uma fonte não confiável, LEMBRE-SE o Openkore oficial é gratuito)

**Comment by TolkienLabel** [comment]
Eu uso o Openkore Premium porém é basicamente a mesma coisa que o normal 
Você desativou o plugin eventMacros das configurações do openkore?
Desativei ? lá não fala nada de desativar
To tentando upar um sumo

**Comment by vitorsilverio** [comment]
Esses openkore Premiums vem com menos plugins padrões, já achei muito deles que não podem rodar o eventMacros.
Você precisa ter todos os plugins padrões do openkore: macro, eventMacros, xConf, etc ou não vai funcionar

**Comment by TolkienLabel** [comment]
você acha que se eu baixar a pasta plugins padrão do oficial da pra funcionar ?

**Comment by vitorsilverio** [comment]
Este issue será fechado pois não damos suporte ao Openkore não oficial, por favor solicite ao fornecedor do seu openkore que habilite os plugins oficiais, ou utilize a versão oficial

**Comment by vitorsilverio** [comment]
> você acha que se eu baixar a pasta plugins padrão do oficial da pra funcionar ?
Pode ser que sim, pode ser que não. Precisa ver com o fornecedor do seu openkore
