### ISSUE TITLE
Comprar Flechas Arqueiro

### ISSUE THREAD

**Issue by StormGamePlay** [eventMacrosBR/up_1_ao_99_todas_classes-bro#145]
Entra em Loop quando ele vai comprar flechas, já entrei e comprei tem zenys para isso 100kk
Já entrei e vendi todas as flechas pra ver se ele compra sozinho
Já entrei e comprei 2000 flechas e deixei não equipadas
Já entrei e equipei as 2000 flechas
Já comprei 10000 flechas

O Que fazer?

1- Versão 1087.1bf1a97
2- 12/4
3- ######## Debugging options; only useful for developers ########

debug 0
debugPacket_unparsed 0
debugPacket_received 0
debugPacket_ro_sent 0
debugPacket_sent 0
debugPacket_exclude
debugPacket_include
debugPacket_include_dumpMethod
debugDomains
logToFile_Debug
logToFile_Errors
logToFile_Messages
logToFile_Warnings
history_max 50
gameGuard 1
macro_orphans terminate
versao_eventmacro_up_todas_as_classes_bro 1087.1bf1a97
questc2_implementada true
questc3_implementada false
buyAuto Flecha {
	npc payon_in01 5 49
	standpoint
	distance 5
	price
	minAmount 100
	maxAmount 2000
	batchSize
	disabled 0
	zeny > 2000
}

useSelf_item Aljave {
	hp
	sp
	homunculus_hp
	homunculus_sp
	homunculus_dead
	onAction
	whenStatusActive
	whenStatusInactive
	whenFollowing
	spirit
	amuletType
	aggressives
	monsters
	notMonsters
	monstersCount
	stopWhenHit 0
	inLockOnly 0
	notWhileSitting 0
	notInTown 0
	timeout 0
	disabled 0
	inInventory Flecha < 50
	manualAI 0
	notOnAction
}

membroDoEden sim
o_que_estou_fazendo upando
saveMap_sequenciaPraArmazenar
saveMap_desejado
saveMap_posicaoKafra
saveMap_posicaoNpcVenda
saveMap_posicaoNpcPraPocao
naSequenciaDeSalvamento false

current_npc kafra
quest_atual

Erro - 
[Jul 20 05:10:26 2018.43] [eventMacro] Conditions met for automacro 'verificarFlechas', calling macro 'tempMacro44'
[Jul 20 05:10:26 2018.45] [eventmacro log] ===================================
[Jul 20 05:10:26 2018.47] [eventmacro log] Quantidade de flechas insuficiente,
[Jul 20 05:10:26 2018.48] [eventmacro log] Inicializando compras automáticas!!
[Jul 20 05:10:26 2018.50] [eventmacro log] ===================================
[Jul 20 05:10:27 2018.54] Config 'route_randomWalk' já é *nada*
[Jul 20 05:10:27 2018.57] Config 'attackAuto' já é 1
[Jul 20 05:10:28 2018.59] Inicializando vendas automaticas.
[Jul 20 05:10:29 2018.78] Pronto para iniciar a venda de itens
[Jul 20 05:10:31 2018.30] [eventMacro] Error in macro 'tempMacro44'
[eventMacro] Line index of the error '8'
[eventMacro] Script of the line '$condicao_compra = &config(buyAuto_1_zeny)'
[eventMacro] Error message 'Could not separate variable name from value'
[Jul 20 05:10:31 2018.32] Conversa com NPC Vendedor de Ferramentas (0) finalizada.

**Comment by StormGamePlay** [comment]
Ok... Resolvi deletando no config.txt no final as seguintes linhas e reabri e funcionou normalmente.
Favor fechar a duvida >;D

macro_orphans terminate
versao_eventmacro_up_todas_as_classes_bro 1087.1bf1a97
questc2_implementada true
questc3_implementada false
buyAuto Flecha {
	npc payon_in01 5 49
	standpoint
	distance 5
	price
	minAmount 100
	maxAmount 2000
	batchSize
	disabled 0
	zeny > 2000
}

useSelf_item Aljave {
	hp
	sp
	homunculus_hp
	homunculus_sp
	homunculus_dead
	onAction
	whenStatusActive
	whenStatusInactive
	whenFollowing
	spirit
	amuletType
	aggressives
	monsters
	notMonsters
	monstersCount
	stopWhenHit 0
	inLockOnly 0
	notWhileSitting 0
	notInTown 0
	timeout 0
	disabled 0
	inInventory Flecha < 50
	manualAI 0
	notOnAction
}

membroDoEden sim
o_que_estou_fazendo upando
saveMap_sequenciaPraArmazenar
saveMap_desejado
saveMap_posicaoKafra
saveMap_posicaoNpcVenda
saveMap_posicaoNpcPraPocao
naSequenciaDeSalvamento false

current_npc kafra
quest_atual

**Comment by vitorsilverio** [comment]
>**StormGamePlay**: Ok... Resolvi deletando no config.txt no final as seguintes linhas e reabri e funcionou normalmente.
Favor fechar a duvida >;D
