### ISSUE TITLE
não acho viável a quest de bruxo ser feita aumaticamente

### ISSUE THREAD

**Issue by gabx257** [eventMacrosBR/up_1_ao_99_todas_classes-bro#15]
A parte de matar monstros é muito difícil na, minha opinião, para ser automatizada,precisa saber reagir a muitas situações, daria um trabalho tremendo, isso se for possível fazer ela de forma aceitável

**Comment by vitorsilverio** [comment]
Uma solução é mudar o tipo de attack para que ele só attack os agressivos primeiro

**Comment by vitorsilverio** [comment]
A estrategia é atacar os agressivos primeiro, por exemplo os Phens primeiro na sala de água e deixar por ultimo os que atacam se atacarem amigos.

**Comment by vitorsilverio** [comment]
Outra configuração util é essa
http://openkore.com/index.php/RunFromTarget_dist

**Comment by vitorsilverio** [comment]
Para priorizar monstros:
http://openkore.com/index.php/Priority.txt

**Comment by gabx257** [comment]
eu fiz tudo isso já, mas mesmo assim tem grandes chances de não conseguir, mago é uma classe complicada para usar no bot é muito suscetível a ataque,uma solução meio absurda mas talvez funcione é fazer uma mago melee de algum modo

**Comment by vitorsilverio** [comment]
@gabx257  Eu fiz uma sacer do 1 ao 99 usando ela melee, sem aumentar o atack, comprei apenas uma maça boa. Mas ela precisava ficar em mapas sem agressivos e normalmente fora da faixa do level dela. O que ajudava um pouco era os buffs e a cura. Talvez fazer uma build mais focada em dex e utilizar skills em leveis diferentes do 10 ajude a ele dar mais dano por segundo (DPS) e evite que ele apanhe menos

**Comment by gabx257** [comment]
é mas sacer ainda da pra fazer porque tem skills que aumentam dano e tal, mas mago o melhor que tem é desejo arcano para sábio de resto é só por brincadeira,os mapas que eu botei nos paramentos de bruxo são todos não agressivos, então quanto ao up só vendo na pratica, mas a quest de mudança de classe vai ser difícil

**Comment by gabx257** [comment]
se o bot estiver com fen é de boa poderia fazer uma macro para equipar a fen caso ele falhe N vezes durante a conjuração

**Comment by vitorsilverio** [comment]
É uma possibilidade, criar requisitos que facilitem a quest não é ruim. A mais inviável ao meu ver até agora é a de caçador, mas vai chegar um momento que alguém vai tentar fazê-la

**Comment by Nipodemos** [comment]
Dificilmente alguém coloca fen num mago classe 1 que é bot

O máximo que consigo pensar é programar pra dar lanças lvl 1 até matar

**Comment by gabx257** [comment]
mas não vale a pena usar lv 1 porque a animação da skill vai gastar muito tempo, e a quest tem limite de tempo

**Comment by Nipodemos** [comment]
então eu só posso repetir o titulo:
não acho viável a quest de bruxo ser feita aumaticamente

**Comment by vitorsilverio** [comment]
isso são tudo suposições, mas podemos deixar a quest sem essa parte por enquanto até acharmos uma solução ou outra pessoa

**Comment by gabx257** [comment]
sim tem que pegar para ver na pratica

**Comment by Nipodemos** [comment]
vou fechar isso aqui porque a dicussão se encerrou
