### ISSUE TITLE
Preso em 'sairDeMocFild20'

### ISSUE THREAD

**Issue by thewisekuma** [eventMacrosBR/up_1_ao_99_todas_classes-bro#155]
A versão é a mais recente.
Estava com Arruaceiro, 60 e pouco. (ou era musa? vou ser honesto, não lembro, mas um dos dois)
Não há relação direta com o config.txt

Print:
![image](https://user-images.githubusercontent.com/45275749/48925235-5f773680-ee76-11e8-8672-9d6223bcb5a3.png)

Como você pode ver, foi resolvido manualmente com um "move morocc".

**Comment by thewisekuma** [comment]
> eita então essa macro parou de funcionar denovo?
> maldita lug! quer dizer, WP!
> affu
> 
> obrigado pelo report, vc poderia comentar qualquer coisa aqui pra poder me notificar e me lembrar amanhã de corrigir isto? por favor

Obrigado! c:

**Comment by Nipodemos** [comment]
resolvido em  723fe68 (eu espero)
