### ISSUE TITLE
Possivel bug

### ISSUE THREAD

**Issue by gabx257** [eventMacrosBR/up_1_ao_99_todas_classes-bro#16]
eu estava usando a macro de arruaceiro e o openkore não permitiu isso `case(= 1..7)` não lembro o erro exatamente postei acho que em algum dos 20 pullrequest que eu dei hoje na outra macro(desculpa de novo,não sei meche muito bem no github)

**Comment by gabx257** [comment]
era algo com "this should be a numerical value"

**Comment by Nipodemos** [comment]
não permitiu? opa vou alterar então

**Comment by Nipodemos** [comment]
corrigido no ultimo commit
