### ISSUE TITLE
Bug automacro_questLuzDivina

### ISSUE THREAD

**Issue by aDwCarrazzone** [eventMacrosBR/up_1_ao_99_todas_classes-bro#162]
Acredito que seja a versão: 1226.81e2668

Personagem:
Base 41, Classe 36

Não sei se ajuda:
debug 0
debugPacket_unparsed 0
debugPacket_received 0
debugPacket_ro_sent 0
debugPacket_sent 0
debugPacket_exclude
debugPacket_include
debugPacket_include_dumpMethod
debugDomains
logToFile_Debug
logToFile_Errors
logToFile_Messages
logToFile_Warnings
history_max 50
gameGuard 0

Erro: 
[eventMacro] Error in macro 'automacro_questLuzDivina_jaTenhosOsItens_call_block'
[eventMacro] Line index of the error '2'
[eventMacro] Script of the line 'if (config(BetterShopper_1)) do conf BetterShopper_1 none'
[eventMacro] Error message 'unknown sub 'config' (maybe you typed wrong?)'
[eventMacro] Conditions met for automacro 'questLuzDivina_jaTenhosOsItens', calling macro 'automacro_questLuzDivina_jaTenhosOsItens_call_block'

Não seria:
Acredito que tenha faltado um & em config.
if (&config(BetterShopper_1)) do conf BetterShopper_1 none #desabilitar

**Comment by Nipodemos** [comment]
:fearful: nao acredito que deixei passar algo tão bobo

**Comment by aDwCarrazzone** [comment]
Acontece. :)

**Comment by aDwCarrazzone** [comment]
Fechando.
