### ISSUE TITLE
Acertar as quests de classe 2

### ISSUE THREAD

**Issue by vitorsilverio** [eventMacrosBR/up_1_ao_99_todas_classes-bro#2]
Já coloquei os itens requisitos para as quests na primeira parte de parametrização, agora preciso definir os scripts das quests

**Comment by Nipodemos** [comment]
ok

**Comment by Nipodemos** [comment]
o que seria os scripts das quests? vc fala de uma macro pra fazer a quest toda né?

**Comment by vitorsilverio** [comment]
cada quest de mudança de classe

**Comment by Nipodemos** [comment]
Vamos deixar isso pra depois, só irá ser feito no final de tudo, quando o resto da macro tiver perfeita
