### ISSUE TITLE
[Melhoria] melhorar macro de up

### ISSUE THREAD

**Issue by vitorsilverio** [eventMacrosBR/up_1_ao_99_todas_classes-bro#26]
Uma proposta de refatoração da auto macro de up que atualmente é assim:
```
automacro UpClasse {
	BaseLevel != 99
	ConfigKeyNot quest_eden em_curso
	ConfigKeyNot quest_eden terminando
	ConfigKeyNot In_saveMap_sequence true
	ConfigKeyNot virarClasse2 true
	ConfigKeyNot virarClasse2T true
	ConfigKeyNot esperarFazerQuest true
	ConfigKeyNot lockMap $mapa{lockMap}
	exclusive 1
	priority 20 #baixa prioridade
	timeout 30
	JobIDNot 0 #Ou o campo de treinamento fica louco
    call upar
}
```
Para algo mais simples e limpo que no futuro seja mais facil para incluir quests ou situações que não triggem ela e atrapalhe tudo
```
automacro UpClasse {
	BaseLevel >1
	ConfigKeyNot ocupadoParaUpar
	ConfigKeyNot lockMap $mapa{lockMap}
	exclusive 1
	priority 20 #baixa prioridade
	timeout 30
    call upar
}

```

**Comment by Nipodemos** [comment]
pra fazer isso basicamente tem que adicionar em vários lugares esse `do conf -f ocupadoPraUpar true`
vai dar um trabalinho mas é a melhor coisa a se fazer

pior que hoje nao vai dar pra eu mexer

**Comment by vitorsilverio** [comment]
Só deixei aberto como lembrete de melhoria, não é urgente essa mudança

**Comment by Nipodemos** [comment]
Na minha humilde opinião, fica mais fácil e legível do jeito que tá, limitando a automacro de up assim

do que colocar em dezenas de automacros , repito, dezenas de automacros as linhas 
`do conf -f ocupadoPraUpar true`
e 
`do conf -f ocupadoPraUpar false`

daria muito trabalho praticamente a toa, e tem grande chance de a gente ter que ficar dias e dias corrigindo erros de algum lugar que a gente tenha esquecido de colocar

**Comment by vitorsilverio** [comment]
Ainda acho que da para melhorar, mas ainda não pensei exatamente como

**Comment by Nipodemos** [comment]
@vitorsilverio posso fechar esse issue?
