### ISSUE TITLE
Builds skills/stats todas classes

### ISSUE THREAD

**Issue by vitorsilverio** [eventMacrosBR/up_1_ao_99_todas_classes-bro#3]
Preciso definir as builds de todas as classes

**Comment by gabx257** [comment]
Então eu poderia fazer,já tenho uma parte do de mago/bruxo que eu fiz para upar um char,só não sei onde pegar os nomes no formato "MG_FIREBOLT"(não sei como chamam)

**Comment by Nipodemos** [comment]
se vc conseguir a do bruxo, ja vai ajudar muito
esse formato é chamado HANDLE (em letra maiuscula mesmo)

eu posso fazer do sábio, amo a classe

**Comment by gabx257** [comment]
Vou fazer o de Bruxo aqui então acabei de achar o arquivo na pasta do openkore com todos os nomes hehe

**Comment by Nipodemos** [comment]
e seis meses depois, ainda não encontramos builds pra todas as classes haahah

**Comment by vitorsilverio** [comment]
Fechando esse pois apesar de não termos builds para todas as classes, já existe uma implementação para multibuilds para uma classe
