### ISSUE TITLE
[Alquimista] Algumas mudanças necessárias

### ISSUE THREAD

**Issue by vitorsilverio** [eventMacrosBR/up_1_ao_99_todas_classes-bro#30]
- [x] Desativar compra de poção laranja antes de ser alquimista, ou seja, como mercador
- [x] Arrumar o better shopper para usar a criação de blocos em vez de criar dentro da quest

**Comment by vitorsilverio** [comment]
IDarmaIntermediario => 16005
Não existe esse id para o alquimista

**Comment by Nipodemos** [comment]
muito estranho, deveria existir
![ID Certa](https://i.imgur.com/unsv22O.png)

**Comment by Nipodemos** [comment]
esse primeiro aí eu acabei de mandar um commit

**Comment by Nipodemos** [comment]
pronto, teroricamente os dois estão resolvidos

**Comment by Nipodemos** [comment]
já pode fechar esse issue?

**Comment by vitorsilverio** [comment]
esqueci dele
