### ISSUE TITLE
buyAuto não dá suporte pra ID

### ISSUE THREAD

**Issue by Nipodemos** [eventMacrosBR/up_1_ao_99_todas_classes-bro#31]
olha:
![Carregando imagem...](https://i.imgur.com/2409PoB.png)

502 é a id da pot laranja, ele ta indo comprar, mas não tá encontrando, vai ter que ser o nome mesmo

**Comment by Nipodemos** [comment]
corrigido... infelizmente parece que não da suporte, aconteceu aí com voce?

**Comment by vitorsilverio** [comment]
buyAuto da sim suporte a ID, as vezes o kore buga, basta reiniciar que volta funcionar

**Comment by Nipodemos** [comment]
sério? affu kkkkkk
mudei a toa então

**Comment by vitorsilverio** [comment]
Agora deixa, acho que deve bugar menos

**Comment by Nipodemos** [comment]
é
