### ISSUE TITLE
[TODO] migrar tudo que tem & e tem a ver com inventário para ID

### ISSUE THREAD

**Issue by Nipodemos** [eventMacrosBR/up_1_ao_99_todas_classes-bro#46]
dessa forma teremos um código ainda mais a prova de erros 😄

**Comment by vitorsilverio** [comment]
-[ ] Revisar quest do Eden
-[ ] Revisar campo de treinamento
-[ ] Revisar configuração de itens
-[ ] Revisar todas as quests da classe 2
-[ ] Revisar as quests de itens

**Comment by Nipodemos** [comment]
pronto
