### ISSUE TITLE
[Melhoria] trocar os `do conf -f` por uma macro que verifica se valor está diferente primeiro

### ISSUE THREAD

**Issue by vitorsilverio** [eventMacrosBR/up_1_ao_99_todas_classes-bro#47]
Utilizar essa macro por exemplo

```perl
#Macro que atualiza config apenas quando o valor novo é diferente do atual
#param[0]: config
#param[1]: valor
macro atualizarConfig {
    if (&config($.param[0]) != $.param[1]) do conf -f $.param[0] $.param[1]
}
```

**Comment by Nipodemos** [comment]
ei @vitorsilverio , vc ainda considera isso uma solução boa?
se ainda considerar to pensando em editar e colocar isso

**Comment by vitorsilverio** [comment]
Não sei se isso faria ganhar algum processamento ou clareza no codigo, porem se quisermos adicionar alguma lógica para logar quando isso ocorrer nessa macro facilitaria a vida

**Comment by Nipodemos** [comment]
em processamento não viu
só que toda vez que vc configura algo, ele já aparece na tela, então pelo menos no momento, não consigo pensar em função nenhuma a mais

**Comment by vitorsilverio** [comment]
como não vamos fazer nenhum log disso no momento eu vou fechar
