### ISSUE TITLE
Definir mapas de up para todas as classes

### ISSUE THREAD

**Issue by vitorsilverio** [eventMacrosBR/up_1_ao_99_todas_classes-bro#5]
Considerar os melhores mapas para conseguir os itens das quests

**Comment by Nipodemos** [comment]
qual text editor vc usa?

**Comment by vitorsilverio** [comment]
no linux VIM, no windows notepad++

**Comment by Nipodemos** [comment]
ja tem uma lista padrão de mapas para todas as classes, acredito que esse issue pode ser fechado
