### ISSUE TITLE
[Melhoria] Deixar a compra de poções laranjas opcional

### ISSUE THREAD

**Issue by vitorsilverio** [eventMacrosBR/up_1_ao_99_todas_classes-bro#66]
Apesar de muitos acharem utei tem uns que reclamam

**Comment by Nipodemos** [comment]
muita treta vixi

**Comment by Nipodemos** [comment]
vamos fazer assim:
enquanto for classe 1, sempre vai estar deesativado

mas quando for classe 2, aí o usuário poderá ter a opção
vo ver se mando um push agora

**Comment by vitorsilverio** [comment]
Eu ainda considero mega util

**Comment by Nipodemos** [comment]
pronteo, feito a um bom tempo

agora a compra de poções é opcional, e classes que não precisam não tem
