### ISSUE TITLE
tretas que os usuários reclamam

### ISSUE THREAD

**Issue by Nipodemos** [eventMacrosBR/up_1_ao_99_todas_classes-bro#67]
# problema na build do arruaceiro:

2. Ele não reconhece a skill Sword Mastery (Skill ID# 2) e nem a Gangster's Paradise, nem Compulsion Discount

 

Habilidade 'RG_SWORDMASTERY' desconhecida em 'RG_SWORDMASTERY 10'; desativando skillsAddAuto

Habilidade 'RG_GANGSTERSPARADISE' desconhecida em 'RG_GANGSTERSPARADISE 1'; desativando skillsAddAuto

Habilidade 'RG_COMPULSIONDISCOUNT' desconhecida em 'RG_COMPULSIONDISCOUNT 5'; desativando skillsAddAuto

# problema no eden do templario:

Quando o Templario completa a quest do eden e ele vai escolher o equipamento Entre Sabre III Lança I E uma espada ele não escolhe nenhum

# talvez o arruaceiro aguenta stapo:

4. O rogue guenta ve_fild07 de boa sim, só evitar as plantas que batem forte e tem muito hp, é so colocar no mon_control:

 

Drosera -1 0 0 ( 0.33% xp no level 90)
Muscipular -1 0 0 (0.40% de xp no level 90)

 

Desse modo ele só mata os Stapos (0.33% de xp no level 90), que tem menos hp e quase nunca consegue ultrapassar a esquiva do rogue para acertar.

Testei esse método do level 81-90 e tá tranquilo, a média de xp/hora é muito maior que gef_fild06.

# gente cobrando macro do caçador:
Opa, ótimo trabalho cara, alguma previsão para a implementação da quest de caçador?

# treta quest eden 60
Durante a quest do Eden em Umbala, ele catou todos os itens já, porém ele continua no mapa catando estes e não atualiza a macro para retornar ao éden.

No console do openkore, ele já está com a informação assim

 

items_control.txt: '7196' is 5 1 0
items_control.txt: '7100' is 7 1 0
Config 'o_que_estou_fazendo' já é quest_eden60_coletandoItens
 
E já tem 10 de cada pelo menos como exemplo.

solução:
Então, olhei na eventMacro e notei que lá tem uma linha falando que ele conclui essa parte se estiver com o HP > 80%. Usei umas poções e ele foi. Seria interessante remover essa linha no código original para assim que ele obter os itens necessários, já partir pro Eden e concluir a quest ao invés de continuar batendo lá enquanto estiver com menos de 80% de HP.

# "já tentou de tudo, mas sempre dá problema"

Bem, como disse, refiz os procedimentos....Porém oq eu observo é que se eu não ficar monitorando, o bot sempre vai parar em um local.

 

Ex: no campo do aprendiz, ele ativa a macro da missão de matar o lunatico, mas ele só mata poring, então tenho que dar reload all ou reload mon_control, pra ele fluir...

 

bem, cheguei a fazer a primeira quest dos equipamentos do eden, porém meu bot voltou para payon e ta matando esporo lvl 20, é isso mesmo que tem que acontecer?

 

Quando dou reload all, esta aparecendo o seguinte erro:

 

Todos os arquivos foram carregados.
[eventMacro] Conditions met for automacro 'init', calling macro 'tempMacro824'
Checando algumas coisas...
Tudo certo.
Checando algumas coisas...
Tudo certo.
items_control.txt: '510' is 7 1 0
items_control.txt: '957' is 10 1 0
items_control.txt: '932' is 10 1 0
items_control.txt: '958' is 10 1 0
Config 'questc2_implementada' já é true
[eventMacro] Error in macro 'tempMacro824'
[eventMacro] Line index of the error '11'
[eventMacro] Script of the line 'if (&config(questc2_implementada != true)) {'
[eventMacro] Error message 'syntax error in if statement'
[eventMacro] Conditions met for automacro 'versao', calling macro 'tempMacro768'
[eventmacro log]

# o problema de não atacar denovo affu haha

https://imgur.com/mlmTwwr

https://imgur.com/Kmmt1St

 

Sou novo no openkore e mais novo ainda nos macros e plug-ins, alguém poderia me ajudar ?? 

O bot não ataca, só fica andando pelo mapa :(

HELP!!!

**Comment by Nipodemos** [comment]
vou deixar aqui porque eu SEMPRE esqueço dessas tretas, agora nao esqueço mais

**Comment by vitorsilverio** [comment]
Parece um show de horrores e cada um merece seu proprio issue

**Comment by Nipodemos** [comment]
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
fiquei com preguiça de um issue pra cada, ai organizei por titulo mesmo

**Comment by Nipodemos** [comment]
# noviço não se cura:

Reparei que o up do noviço, ele não está usando curar em si nem os buffs, não sei se fiz errado e irei revisar o eventMacro quando chegar do trabalho, mas pode dar uma olhada também?

**Comment by vitorsilverio** [comment]
Sempre se curou

**Comment by vitorsilverio** [comment]
Eu não consigo saber o que já foi resolvido ou não com um issue para tudo

**Comment by vitorsilverio** [comment]
Followed by #70 #71 #72 #73 #74 #75

**Comment by Nipodemos** [comment]
opa, isso aew
