### ISSUE TITLE
problema na build do arruaceiro:

### ISSUE THREAD

**Issue by vitorsilverio** [eventMacrosBR/up_1_ao_99_todas_classes-bro#69]
Ele não reconhece a skill Sword Mastery (Skill ID# 2) e nem a Gangster's Paradise, nem Compulsion Discount
Habilidade 'RG_SWORDMASTERY' desconhecida em 'RG_SWORDMASTERY 10'; desativando skillsAddAuto

Habilidade 'RG_GANGSTERSPARADISE' desconhecida em 'RG_GANGSTERSPARADISE 1'; desativando skillsAddAuto

Habilidade 'RG_COMPULSIONDISCOUNT' desconhecida em 'RG_COMPULSIONDISCOUNT 5'; desativando skillsAddAuto

**Comment by Nipodemos** [comment]
acabei de descobrir, que no nosso repositório ele nem tem essas skills, o cara que modificou manualmente e veio reclamar

aff

**Comment by vitorsilverio** [comment]
TROLLADO
