### ISSUE TITLE
talvez o arruaceiro aguenta stapo:

### ISSUE THREAD

**Issue by vitorsilverio** [eventMacrosBR/up_1_ao_99_todas_classes-bro#71]
O rogue guenta ve_fild07 de boa sim, só evitar as plantas que batem forte e tem muito hp, é so colocar no mon_control:
Drosera -1 0 0 ( 0.33% xp no level 90)
Muscipular -1 0 0 (0.40% de xp no level 90)

Desse modo ele só mata os Stapos (0.33% de xp no level 90), que tem menos hp e quase nunca consegue ultrapassar a esquiva do rogue para acertar.

Testei esse método do level 81-90 e tá tranquilo, a média de xp/hora é muito maior que gef_fild06.

gente cobrando macro do caçador:

**Comment by Nipodemos** [comment]
precisamos definir um método do bot usar o aeroplano para chegar aí
mas do jeito que está pode ser complicado

**Comment by vitorsilverio** [comment]
Se mudarmos agora para stapo será que o bot vai?

**Comment by Nipodemos** [comment]
somente um arruaceiro aguentaria, e teríamos que configurar pra ignorar drosera e muscipular
e usar o plugin runFromMonster pra se ter máxima eficiencia

**Comment by Nipodemos** [comment]
ou seja nada prático

**Comment by Nipodemos** [comment]
será que isso rola ainda? vc fez toda aquela parada de submodules justamente por causa disso, pra colocar plugins que possamos precisar

**Comment by vitorsilverio** [comment]
tem que acertar para usar esse plugin e tambem o better shopper sem baixar, a ideia de empacotar foi apra isso, falta o animo para fazer. Quando ficarmos sem o bettershopper automatico meio que vai obrigar

**Comment by vitorsilverio** [comment]
Com o #83 pronto já é possível finalmente fazer

**Comment by Nipodemos** [comment]
Finally heheh

**Comment by vitorsilverio** [comment]
Vamos ou não vamos colocar o arruaceiro no stapo level 90+?

**Comment by Nipodemos** [comment]
melhor não
vai morrer muito fácil, e vai ter momento que vai bugar por causa da quantidade de drosera que ele vai precisar evitar
