### ISSUE TITLE
treta quest eden 60

### ISSUE THREAD

**Issue by vitorsilverio** [eventMacrosBR/up_1_ao_99_todas_classes-bro#72]
Durante a quest do Eden em Umbala, ele catou todos os itens já, porém ele continua no mapa catando estes e não atualiza a macro para retornar ao éden.

No console do openkore, ele já está com a informação assim

items_control.txt: '7196' is 5 1 0
items_control.txt: '7100' is 7 1 0
Config 'o_que_estou_fazendo' já é quest_eden60_coletandoItens

E já tem 10 de cada pelo menos como exemplo.

solução:
Então, olhei na eventMacro e notei que lá tem uma linha falando que ele conclui essa parte se estiver com o HP > 80%. Usei umas poções e ele foi. Seria interessante remover essa linha no código original para assim que ele obter os itens necessários, já partir pro Eden e concluir a quest ao invés de continuar batendo lá enquanto estiver com menos de 80% de HP.

**Comment by Nipodemos** [comment]
então.... tem que ser pensado um método ainda, porque u coloquei essa condição de pelo menos 80% de hp para que o bot se recupere caso morra, mas o arruaceiro tava com esquiva tão boa, e as pot, que não morria, e tamb´m nao chegou aos 80% de hp
talvez separar um QuestHuntComplete do CurrentHP sirva

**Comment by vitorsilverio** [comment]
Acho que me lembro disso nos meus arruaceiros, mas não tinha poção configurado até o level 70+

**Comment by Nipodemos** [comment]
nossa já tinha até esqeucido isso

**Comment by Nipodemos** [comment]
isso é desnecessário na minhao opinião, é bem raro de acontecer
