### ISSUE TITLE
"já tentou de tudo, mas sempre dá problema"

### ISSUE THREAD

**Issue by vitorsilverio** [eventMacrosBR/up_1_ao_99_todas_classes-bro#73]
Bem, como disse, refiz os procedimentos....Porém oq eu observo é que se eu não ficar monitorando, o bot sempre vai parar em um local.

Ex: no campo do aprendiz, ele ativa a macro da missão de matar o lunatico, mas ele só mata poring, então tenho que dar reload all ou reload mon_control, pra ele fluir...

bem, cheguei a fazer a primeira quest dos equipamentos do eden, porém meu bot voltou para payon e ta matando esporo lvl 20, é isso mesmo que tem que acontecer?

Quando dou reload all, esta aparecendo o seguinte erro:

Todos os arquivos foram carregados.
[eventMacro] Conditions met for automacro 'init', calling macro 'tempMacro824'
Checando algumas coisas...
Tudo certo.
Checando algumas coisas...
Tudo certo.
items_control.txt: '510' is 7 1 0
items_control.txt: '957' is 10 1 0
items_control.txt: '932' is 10 1 0
items_control.txt: '958' is 10 1 0
Config 'questc2_implementada' já é true
[eventMacro] Error in macro 'tempMacro824'
[eventMacro] Line index of the error '11'
[eventMacro] Script of the line 'if (&config(questc2_implementada != true)) {'
[eventMacro] Error message 'syntax error in if statement'
[eventMacro] Conditions met for automacro 'versao', calling macro 'tempMacro768'
[eventmacro log]

**Comment by Nipodemos** [comment]
resolvido esses dois erros
um era do mconf, outro era apenas erro de sintaxe
