### ISSUE TITLE
o problema de não atacar denovo affu haha

### ISSUE THREAD

**Issue by vitorsilverio** [eventMacrosBR/up_1_ao_99_todas_classes-bro#74]
https://imgur.com/mlmTwwr

https://imgur.com/Kmmt1St

Sou novo no openkore e mais novo ainda nos macros e plug-ins, alguém poderia me ajudar ??

O bot não ataca, só fica andando pelo mapa :(

HELP!!!

**Comment by Nipodemos** [comment]
resolvido aqui : #77
