### ISSUE TITLE
noviço não se cura:

### ISSUE THREAD

**Issue by vitorsilverio** [eventMacrosBR/up_1_ao_99_todas_classes-bro#75]
Reparei que o up do noviço, ele não está usando curar em si nem os buffs, não sei se fiz errado e irei revisar o eventMacro quando chegar do trabalho, mas pode dar uma olhada também?

nipodemos, em 25 Jan 2018 - 12:01, disse:

segundo testes, funcionou normal uai, qual o nível atual de curar seu sacer tem?

Está nível 10. O aumentar agilidade vi que está normal, porém ele realmente não se cura.

**Comment by Nipodemos** [comment]
vou fechar esse issue porque provavelmnte é cagada de usuario
