### ISSUE TITLE
essa parte do site ainda nao rolou

### ISSUE THREAD

**Issue by Nipodemos** [eventMacrosBR/up_1_ao_99_todas_classes-bro#76]
![image](https://user-images.githubusercontent.com/11494727/35472743-0a875264-035c-11e8-8f8c-247768ec35d8.png)

**Comment by vitorsilverio** [comment]
Não entendo porque tabela não vai de jeito algum

**Comment by vitorsilverio** [comment]
Resolvido, bastava um espaço entre o titulo e a tabela
