### ISSUE TITLE
xConfConfiguratedOrNot deve ser removido

### ISSUE THREAD

**Issue by vitorsilverio** [eventMacrosBR/up_1_ao_99_todas_classes-bro#81]
O usuário bruninjaman está tendo problemas com a macro pois o 
```
using File::Copy
```
Aparentemente não está mais disponivel no openkore, não sei se esse problema é apenas dele. mas de qualquer forma não damos suporte para quem não tm openkore atualizado essa função para checar se xconf está instalado não é mais necessário uma vez que ele já é padrão e não fazemos checagem para os plugins padrões.

**Comment by Nipodemos** [comment]
eu nem fui notificado que vc tinha criado esse issue
que estranho

**Comment by vitorsilverio** [comment]
estranho mesmo, o github ta demorando entregar os emails nesse repositorio as vezes
