### ISSUE TITLE
bugs reportados que devem ser corrigidos

### ISSUE THREAD

**Issue by Nipodemos** [eventMacrosBR/up_1_ao_99_todas_classes-bro#82]
bruninjaman (IP: 189.61.42.109)

Agora to usando mais o wxstart msm, consegui pegar 3 arrua no 99 com a event macro. Os únicos problemas que tive foi na hora de rebornar o autobuy continuava ativado ai ele ia pro local de fazer a troca com meu outro personagem e quando ele chegava ele ja queria voltar pra payon. tentei desligar o ai e ligar o ai quando já tivesse com a troca aberta, ele fazia a troca normal mas depois da troca com 0 de peso e 1285000 de zeny ele continuava mandando pm pro meu mercador querendo trocar. E durante a troca ele falava que precisava de 0 zenys, fechei o bot e pulei essa parte mudando a config pra preparado para o reborn. ele conseguiu rebornar normal(quase normal ele fico indo pro aeroplano e voltando pro lugar da quest algumas vezes) mas ai quando ele virou aprendiz T ele fico bugado em morroc no mapa da direta eu acho(ele tava com 0 de zeny e não conseguia ir apé para prt_fild01). Entrei neles manualmente e upei pro lvl 10 de job. Eles tentaram fazer a "quest" pra virar gatuno T, mas parece que quando ele tentava usar o "talknpc <x> <y>" as coordenadas do npc estavam erradas, eu loguei nele e falei com npc manualmente. o resto ele fez sozinho até o 50 de job.. ele tbm não conseguiu virar desordeiro. mas essa parte foi fácil só virei manualmente tbm. O resto ele fez tudo sozinho(não testei quest de arruaceiro pois eles já eram arruaceiros quando comecei a usar a eventmacro).

**Comment by vitorsilverio** [comment]
muito estranho, eu chequei o local de todos npcs da classe 2T

**Comment by vitorsilverio** [comment]
E teoricamente o local de todos da classe 1T é o mesmo e não tem opção para escolher

**Comment by Nipodemos** [comment]
by the way, a quest de classe2t ta realmente bugada mesmo, vou mexer nela agora

**Comment by vitorsilverio** [comment]
As coordenadas estão realmente erradas?

**Comment by Nipodemos** [comment]
não
as coordenadas não
mas vc não precisa falar com aquele cara antes, só ir direto pro livro
tinha uma resposta pro livro que não tava na macro
e também tinha que usar a teleportadora pra sair de lá, aí coloquei também
agora que to vendo que não subi pro github o commit, quando chegar em casa faço isso

**Comment by Nipodemos** [comment]
esse problema do autobuy foi resolvido
problema de virar classe 2 também resolvido
