### ISSUE TITLE
Plugins externos agora devem ser submodulos

### ISSUE THREAD

**Issue by vitorsilverio** [eventMacrosBR/up_1_ao_99_todas_classes-bro#83]
Contexto
------------
A nossa abordagem de instalação automática de plugins pode causar erros no openkore, o melhor será disponibiliza-los juntos ou num zip separado para que os usuários utilizem. Podemos apenas checar se existem e estão configurados. Além disso ter que manter cada plugin que precisarmos em http num servidor externo é inviável, principalmente para manutenção e custo sendo que existem no github.

Algumas tarefas a serem executadas:
- [x] Remover o download dos plugins da macro
- [x] Fazer apenas a configuração no sys.txt e verificar se o plugin se encontra na pasta plugins
- [x] Empacotar os plugins para distribuição junto as macros

**Comment by vitorsilverio** [comment]
> Nipodemos @Nipodemos 15:36
aí oq pode ser feito
quando o travis criar o zip
ele cria o zip com a pasta control e pasta plugins
que aí os cara precisa só jogar por cima

Para não esquecer a sugestão

**Comment by vitorsilverio** [comment]
empacotados

**Comment by Nipodemos** [comment]
aliás, é realmente necessário empacotar no zip o plugin bettershopper? porque ele já instala por padrão por enquanto

seria interessante só mandar o plugin quando for necessário colocar manualmente

**Comment by vitorsilverio** [comment]
A assinatura do servidor que esta hospedado o que instalamos automatico logo vai acabar

**Comment by Nipodemos** [comment]
Oh beleza em
dificultou nossa vida um pouco

**Comment by vitorsilverio** [comment]
Plugins totalmente separados da macro agora
