### ISSUE TITLE
Considerações para arquerio by @rafaelldavid

### ISSUE THREAD

**Issue by vitorsilverio** [eventMacrosBR/up_1_ao_99_todas_classes-bro#88]
Segue as recomendações por: @rafaelldavid
> Abrir a aljava que ganha ao virar arqueiro e equipar as flechas, senão ele vai pro mapa do up e fica tentando atacar e não consegue... (fiz manualmente pelo console do kore)
> usei o is id_da_flecha
> eq id_da_flecha
> não sei como isso daria pra incluir na macro
> Configurar pra ele comprar mais flechas, quando as dele acabar...
> payon 159 96
> tem outros npcs que peguei daqui https://pt.ragnaplace.com/bRO/item/1750/Flecha
> equipAuto Flecha (right ou left hand?)
```
buyAuto Flecha {
    npc payon 159 96
    standpoint
    distance 5
    price
    minAmount 25
    maxAmount 2000
    batchSize
    disabled 0
   }
```
```
attackDistanceAuto 1
```
```
useSelf_item Erva Vermelha, Maçã {
    hp < 80%
    sp
    homunculus_hp
    homunculus_sp
    homunculus_dead
    onAction
    whenStatusActive
    whenStatusInactive
    whenFollowing
    spirit
    amuletType
    aggressives
    monsters
    notMonsters
    monstersCount
    stopWhenHit 0
    inLockOnly 0
    notWhileSitting 0
    notInTown 0
    timeout 0
    disabled 0
    inInventory
    manualAI 0
}
```
> Usei esse pq salgueiro ancião cai muito isso, ajuda e diminui as idas ao storage... rs

**Comment by Nipodemos** [comment]
mandado por rafaeldavid tambem
useSelf_skill Concentração {
    lvl 10
    maxCastTime 0
    minCastTime 0
    hp
    sp > 10%
    homunculus_hp
    homunculus_sp
    homunculus_dead
    onAction
    whenStatusActive
    whenStatusInactive Concentração
    whenFollowing
    spirit
    amuletType
    aggressives
    monsters
    notMonsters
    monstersCount
    stopWhenHit 0
    inLockOnly 0
    notWhileSitting 1
    notInTown 1
    timeout 0
    disabled 0
    inInventory
    manualAI 0
}

**Comment by vitorsilverio** [comment]
> Mudei o lugar de comprar flechas quando tá upando em iz_dun00
```
buyAuto Flecha {
    npc izlude_in 60 127
    standpoint
    distance 5
    price
    minAmount 25
    maxAmount 5000
    batchSize
    disabled 0
}
```
> Pq senão ele tela pra izlude, tela pra payon, compra flecha, tela de volta pra izlude pra poder pegar o barco pra ir upar... rs

**Comment by vitorsilverio** [comment]
```
attackSkillSlot Rajada de Flechas {
    lvl 10
    dist 1.5
    maxCastTime 0
    minCastTime 0
    hp
    sp > 15%
    homunculus_hp
    homunculus_sp
    homunculus_dead
    onAction attack
    whenStatusActive
    whenStatusInactive
    whenFollowing
    spirit
    amuletType
    aggressives
    previousDamage
    stopWhenHit 0
    inLockOnly 0
    notInTown 0
    timeout 0
    disabled 0
    monsters
    notMonsters
    monstersCount
    maxAttempts 0
    maxUses 1
    target_hp
    target_whenStatusActive
    target_whenStatusInactive
    target_deltaHp
    inInventory
    isSelfSkill 0
    equip_topHead
    equip_midHead
    equip_lowHead
    equip_leftHand
    equip_rightHand
    equip_leftAccessory
    equip_rightAccessory
    equip_robe
    equip_armor
    equip_shoes
    equip_arrow
    manualAI 0
}
```

**Comment by Nipodemos** [comment]
Algumas considerações sobre o esboço pra quest c-2:

1) Garras de Lobo: quando vc tá upando e fazendo quest eden (lvl 35, acho), vc pega algumas garras lá no deserto, seria bom configurar pra armazenar ele ao invés de vender...

2) Troncos: O mapa logo abaixo dos Salgueiros Anciões, em Payon, tem aquelas mobs 'Guardião da Floresta. Eles dropam troncos com 20% de chance. Dá pra juntar rápido... Busquei os meus lá e foi sussa...

3) Ervas Brancas: idem Garras de Lobo (não sei onde dropa, mas quando tava classe 50, fui no storage e já tinha algumas lá.

4) Bico de Ave: dá pra dropar de Condor. Mapa abaixo de Morocc é cheio...

5) Ossos: Zumbis dropam, dá pra guardar ou ir caverna de Payon.

6) Ervas Verdes: tem na caverna de Payon as plantinhas...

7) Caninos Venenosos: dá pra pegar em Payon (pay_fild02). Tem uma porrada de cobras lá que dropam (tem muito mais bots do que cobras lá, mas eles largam todo loot no chão e sempre telam quando vc aparece... kkkkkkkkkkkkk).

8) Erva Vermelha: dropa bastante quando vc tá upando nos Salgueiros Anciões.

9) Couro de Aninal: idem Garras de Lobo (item 1)

10) Chifre de Dokebi: Não tenho muitas infos de onde dropam. Sei de pay_dun04, mas lá também tem Nove Caldas, Esqueleto General, então pode ser complicado...

11) Pedaço de Casca de Ovo: qualquer mapa que tenha ovo! Pode ser no mapa abaixo de Morocc...

12) Felpas: Fabre... rsrs

13) Casca: Chon chon

14) Pele de Verme: lugar mais rápido - formigueiro infernal. Alternativa: mapa dos Guardiões da Floresta (abaixo dos Salgueiros Anciões)

15) Ervas Amarelas: sempre dropam dos mobs, sempre tenho algumas.

16) Dente de Morcego: Também no mapa dos zumbis.

17) Muco Pegajoso: cai praticamente em todo lugar... kkkkkkkkkkkkk

18) Pata de Urso: perto dos Salgueiros Anciões

19) Espinhos de Porco Espinho: Caramelo, pode ser em pay_fild07

20) Avelã: Koko em pay_fild09

21) Cauda de Yoyo: Yoyo em prt_fild03

**Comment by Nipodemos** [comment]
esse issue finalmente pode ser fechado :D
todas as coisas faladas aqui já foram implementadas
