### ISSUE TITLE
Quest templario verificar equipes ao termino

### ISSUE THREAD

**Issue by vitorsilverio** [eventMacrosBR/up_1_ao_99_todas_classes-bro#90]
twistedevill @twistedevill 17:56
report aqui!
depois que ele vira templario de espadachim ele nao equipa os itens do set de valhalla
e fica upando sem arma, na mao
sem o set tbm

**Comment by Nipodemos** [comment]
Após o commit 67ed88f154a5d1bb3f89b826a11c4a972871c815
agora todas as classes, após virar classe 2 eles equipam os equips eden :smile:
