### ISSUE TITLE
Éden - Equipamentos 

### ISSUE THREAD

**Issue by lksoliver** [eventMacrosBR/up_1_ao_99_todas_classes-bro#92]
**Quests perfeitas**, _porem os personagens não equipa o éden do respectivo level._
**Exemplo** : ele está equipando com o Éden lvl 12, completando o éden lvl 81 ele simplesmente ignora o fato dos itens está na bag e não os equipa.
@lksoliver aqui
é nessa que eu vou :*

**Comment by Nipodemos** [comment]
realmente, ele só equipa os equips de eden do lvl 12 entre os niveis 12 até 26
ocorreria um bug dele acabar equipando equips antigos em cima dos mais novos

**Comment by vitorsilverio** [comment]
É preciso criar uma lógica para a macro autoequipar o equipe mais **FORTE** possível para o level atual, se existisse algum plugin ajudaria bastante

**Comment by Nipodemos** [comment]
resolvido em  a396c3b
